# Generated by Django 4.2.20 on 2025-06-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='token_id',
        ),
    ]
